function createfigure(YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE(YMATRIX1, YMATRIX2, YMATRIX3, YMATRIX4)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 12-May-2016 09:12:08

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','\mu_1');
set(plot1(2),'DisplayName','\mu_2');
set(plot1(3),'DisplayName','\mu_3');
set(plot1(4),'DisplayName','\mu_4');

% Create xlabel
xlabel({'iteration i'});

% Create ylabel
ylabel({'\mu'});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[1 401]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-2 9]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',18);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Position',[0.1357638898823 0.773229373264342 0.0624999990065893 0.13970110066298]);

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix2,'Parent',subplot2,'LineWidth',2);

% Create xlabel
xlabel({'iteration i'});

% Create ylabel
ylabel({'\mu'});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[1 401]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-2 9]);
box(subplot2,'on');
% Set the remaining axes properties
set(subplot2,'FontSize',18);
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix3,'Parent',subplot3,'LineWidth',2);

% Create xlabel
xlabel({'iteration i'});

% Create ylabel
ylabel({'\mu'});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[1 401]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[-2 9]);
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'FontSize',18);
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix4,'Parent',subplot4,'LineWidth',2);

% Create xlabel
xlabel({'iteration i'});

% Create ylabel
ylabel({'\mu'});

% Create title
title({''});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[1 401]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[-2 9]);
box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'FontSize',18);
% Create textbox
annotation(figure1,'textbox',[0.3328125 0.937596492070436 0.366666655894369 0.038011695064067],...
    'String',{'\mu convergence for regularization parameter \xi = 1'},...
    'LineStyle','none',...
    'FontWeight','bold',...
    'FontSize',18);

